export default [
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: +5,
    change7: -3,
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: true,
  },
  {
    id: 1,
    name: "tehran",
    price: "2",
    change24: "3%",
    change7: "3.4%",
    volume: "23",
    contractAddress: "sfadfdsf",
    landlordAddress: "daffadsfds",
    sellPosition: false,
  },
];
